### PR TITLE
Bump version to 1.10.0

### PR DESCRIPTION
**Pull request by SiwyDym**
Bumping version of GJF, related to #11

### CODE REVIEW

**Comment by a1exsh** [comment]
Closing to test github actions, will re-open immediately.

**Comment by SiwyDym** [comment]
Do you know the reason why is broken? `gpg: error reading key: No public key
gpg: keyserver receive failed: No keyserver available` 

The problem lies in the line `gpg --list-keys "$PGP_SIGN_KEY_ID"`, PGP_SIGN_KEY_ID value isn't correct? 

edit:
I checked one more time for the earlier version(1.9.0) and got the same errors. So it looks like the issue can be with the sign key value (PGP_SIGN_KEY_ID).

**Comment by a1exsh** [comment]
@SiwyDym can you please try to update using the latest change from here: https://github.com/a1exsh/google-java-format-git-pre-commit-hook/commit/db927cd5440e8e0e698a28b430b5e16929cbd4bd ?

**Comment by SiwyDym** [comment]
Partially works for `1.9.0`. I gotted warning that given signature is not certified by a trusted signature.  For `1.10.0` doesn't works. 

Also I checking `E77417AC194160A3FABD04969A259C7EE636C5ED` in several [Keyserver examples](https://en.wikipedia.org/wiki/Key_server_(cryptographic)) with 404 as a result, is intended? 

Most probably we should use another signature that is trusted, what do You think?

**Comment by a1exsh** [comment]
Maybe this explains it:
```
$ ./pre-commit 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     40      0 --:--:-- --:--:-- --:--:--    39
pub   rsa4096 2013-11-13 [SC]
      E77417AC194160A3FABD04969A259C7EE636C5ED
uid           [ unknown] Liam Miller-Cushon <cushon@google.com>

gpg: Signature made Wed 31 Mar 2021 11:58:00 PM CEST
gpg:                using RSA key E77417AC194160A3FABD04969A259C7EE636C5ED
gpg: BAD signature from "Liam Miller-Cushon <cushon@google.com>" [unknown]

$ cat ~/.cache/google-java-format-git-pre-commit-hook/google-java-format-1.10.0-all-deps.jar.tmp
Not Found
```

Let's double-check the URL.

**Pull request closed without merging**
